version: "3.9"

services:
  # db:
  #   image: postgres:15
  #   restart: always
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: test
  #     POSTGRES_PASSWORD: test
  #     POSTGRES_DB: test_db
  db:
    env_file: .env.ci
    container_name: peaks-db-1
    image: postgres:16-bookworm
    restart: always
    environment:
      DATABASE_ENGINE: ${DATABASE_ENGINE}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_PORT: ${DATABASE_PORT}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: ${DATABASE_ENGINE}://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${DATABASE_PORT}/${DATABASE_NAME}

volumes:
  postgres_data:
