site_name: The Mountain Peaks API Documentation V1
site_description: "Comprehensive documentation for the Peaks API project."
site_author: "Kajoc"
theme:
  name: "material"
nav:
  - Home: index.md
  - Try it out: try_it_out.md
  - API Reference: api_reference.md
  - Database: database.md
  - Configuration: configuration.md
  - CI/CD: ci_cd.md
  - Security: security.md

