from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from starlette.middleware.sessions import SessionMiddleware
from src.api.peaks import router as peaks_router
from src.api.authentication import router as authentication_router, retrieve_peak_api_secret_key
from dotenv import load_dotenv
import os
import sentry_sdk

# Load environment variables
load_dotenv()
IS_PRODUCTION = os.getenv("PRODUCTION", "FALSE").lower() == "true"

# Initialize Sentry
sentry_sdk.init(
    dsn=os.getenv("SENTRY_DSN"),
    # Add data like request headers and IP for users,
    # see https://docs.sentry.io/platforms/python/data-management/data-collected/ for more info
    send_default_pii=True,
    # Set traces_sample_rate to 1.0 to capture 100%
    # of transactions for tracing.
    traces_sample_rate=1.0,
    # Set profile_session_sample_rate to 1.0 to profile 100%
    # of profile sessions.
    profile_session_sample_rate=1.0,
    # Set profile_lifecycle to "trace" to automatically
    # run the profiler on when there is an active transaction
    profile_lifecycle="trace",
)

app = FastAPI(
    title="Peaks API",
    description="Find data about mountains.",
    version="1.0",
    docs_url=None if IS_PRODUCTION else "/docs",  # Disable Swagger UI
    redoc_url=None if IS_PRODUCTION else "/redoc",  # Disable ReDoc
    openapi_url=None if IS_PRODUCTION else "/openapi.json"
)

# Add session middleware
app.add_middleware(SessionMiddleware, secret_key=retrieve_peak_api_secret_key())

# Include the authentication router
app.include_router(authentication_router, prefix="/auth", tags=["auth"])

# Include the peaks router
app.include_router(peaks_router)

print(app.routes)

# Function to get the static directory
def get_static_directory() -> str:
    """
    Return the path to the static directory where MkDocs site is built.
    It first checks for the container path '/app/docs/site', then falls back to the local 'docs/site'.
    """
    container_static_dir = "/app/docs/site"
    local_static_dir = "docs/site"
    if os.path.exists(container_static_dir):
        return container_static_dir
    elif os.path.exists(local_static_dir):
        return local_static_dir
    else:
        # Optionally, you can log a warning or use a default empty directory
        return local_static_dir  # or raise an error if you prefer


# Mount the static files generated by MkDocs located at "docs/site"
static_dir = get_static_directory()
app.mount("/", StaticFiles(directory=static_dir, html=True), name="documentation")
# @app.get("/")
# def read_root():
#     return